# Generated by Django 6.0.1 on 2026-01-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="x",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(verbose_name="date published"),
        ),
    ]
